import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import LoginForm from '../components/authenticate-form'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Stock Trading Simulator
        </h1>

        <p className={styles.description}>
          Get started with a virtual $100000 and test out your trading strategies
          without wasting a single cent.
        </p>

      <LoginForm />
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
